### ISSUE TITLE
What to do when checksums check fails?

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#495]
For example
scratch install qt5-webkit
Resolving dependencies...
[i] qt5-webkit  
( 1 install )
Continue install package(s)? (Y/n) 
==> Building: qt5-webkit-5.212.0alpha4-1
==> Source found: /var/cache/scratchpkg/sources/qtwebkit-5.212.0-alpha4.tar.xz
==> Source found: /var/cache/scratchpkg/sources/qt5-webkit-bison-3.7.patch
==> Source found: /var/cache/scratchpkg/sources/qt5-webkit-python-3.9.patch
==> Checking checksums...
 -> missing: aa35a52d0a4560753650dd7e06369d6c  qt5-webkit-python-3.9.patch
 -> new    : 539223664200de3afeebafa4f5c4dcd6  qt5-webkit-python-3.9.patch

**Comment by emmett1** [comment]
those checksums error maybe because of incomplete download of source. i already check on my side, checksum provided is already correct. try redownload those source.
you can run `scratch build qt5-webkit --clean` to remove all downloaded sources for `qt5-webkit`.
or you can manually remove unmatch checksums file in `/var/cache/scratchpkg/sources`.

**Comment by temp987349867934876** [comment]
this did not help
now it is 
 -> missing: f852ddcf1cd49354d75084e491783ec0  qt5-webkit-bison-3.7.patch
 -> missing: aa35a52d0a4560753650dd7e06369d6c  qt5-webkit-python-3.9.patch
 -> new    : b3d2f6f1f4aa4c99e57f60fb85c8e8f0  qt5-webkit-bison-3.7.patch
 -> new    : 539223664200de3afeebafa4f5c4dcd6  qt5-webkit-python-3.9.patch

**Comment by emmett1** [comment]
Try use `-m` flag which is for ignoring checksum mismatch.
`scratch install <pkg> -m`

**Comment by temp987349867934876** [comment]
Build success with the secret -m switch!
