### ISSUE TITLE
Standalone document for how to update / add new packages please for newbies

### ISSUE THREAD

**Issue by scsijon** [venomlinux/ports#525]
The jwm package has finally been updated, after a lot of work by it's group, to 2.4.0.

However, what i'd really like is a stand-alone document with a step-by-step instruction of the process we new venomlinux users should use to have packages we find that need updating to be followed please.  I'm seriously confused at the moment how to deal with this.

Also the same for how do we add new (to your system) packages, or do i just add them to my fork and you'll 'magically' be notified? I have at least 20 i use currently that are not in your ports directories and many more i 'interact' with regularly.

Can I take it your use of the word 'ports' mean packages, it's confusing to say the least! The word port to me means a complete set of compiled packages, built together at set versions, and used to create a  '$releasenumber' version of a linux system.

**Comment by emmett1** [comment]
To update the system you need to sync ports and run scratch sysup.

`portsync && scratch sysup`

Then optionally (recommended) to check broken packages due to updates and updating configuration in /etc by running:

`revdep -r` & `updateconf` respectively.

Your ports you can add to official `ports` repository by forking and make Pull Request, then i will get notified to check and merge it. You can add to your github repo for you and everyone to use it if they know it by adding custom repo. But its recommended to add to official repo, so me and everyone can maintain it.

Venom Linux is targetting to be community distro, everyone can maintain ports, update it, fix it, improve it and etc. Just fork and make PR for changes, if its good changes, i will merge it.

In venom linux, `ports` mean a set of buildscript (spkgbuild & its patches and etc) to build packages to install into system. Not the precompiled packages.

I will write guide in the wiki about adding new ports.

**Comment by scsijon** [comment]
thanks for the quick reply

Ok, I think i understand at least part of this, I shall 'have-a-go' and 
see what 'appears' locally and in my fork for now.
